### ISSUE TITLE
amm_program

### ISSUE THREAD

**Issue by Fortunat-G** [raydium-io/raydium-library#1]
I want to know about it
let amm_program = Pubkey::from_str("675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8")?;
     let amm_pool_id = Pubkey::from_str("DSUvc5qf5LJHHV5e2tD184ixotSnCnwj7i4jJa4Xsrmt")?;
What does it refer to specifically?
![20240420-120419](https://github.com/raydium-io/raydium-library/assets/104415931/ea1bf679-81e0-4ea2-ac35-713b9dac0d53)

**Comment by loncrypto** [comment]
Im also having the same issue with this repo. While trying to find pool keys wong keys are being returned for mainnet. Or I am doing some things wrong. Have been trying to solve it out for 5 days but couldnt find any help anywhere.

**Comment by popconst** [comment]
Had the same thing. Ended up using borsh to unpack the accout.data into the AmmInfo struct taken directly from the raydium-amm
