### ISSUE TITLE
Libraries are far from production ready

### ISSUE THREAD

**Issue by shrimpwtf** [raydium-io/raydium-library#4]
These libraries are super outdated and as well as this if you delete cargo.lock or simply run cargo update, the entire codebase will fail to compile because the different libraries have been abandoned at different points over time. Please update your libraries, you cause so many developers to waste countless hours reverse engineering and having to make their own internal libraries to simply interact with your dapps. this is unacceptable.

**Comment by RainRaydium** [comment]
Apologize for the incompleteness of the library. Too busy with other work before. Please check the latest submission. If you have any questions, please let me know. Thank you.
